<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\OpenSans-Medium.ttf" />
    <None Remove="Fonts\Poppins-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entitetslager\Entitetslager.csproj" />
    <ProjectReference Include="..\Servicelager\Servicelager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\OpenSans-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-SemiBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
